
import React, { useState } from 'react';
import MarkdownRenderer from './MarkdownRenderer';
import { ProjectData } from '../types';
import JSZip from 'jszip';
import { GeminiService } from '../GeminiService';
import { useProject } from '../ProjectContext';
import DriftAnalyzer from './DriftAnalyzer';
import CodebaseViewer from './CodebaseViewer';
import { getPluginById } from '../utils/plugins';
import { buildVirtualFileSystem, upsertFileNode, consolidateProjectFiles } from '../utils/projectFileSystem';
import Confetti from './Confetti';
import { useToast } from './Toast';
import { generateMarkdownVault } from '../utils/exportService';

interface KickoffViewProps {
  assets?: string;
  projectData: ProjectData;
  onGenerate: () => void;
  onUpdateProject: (data: Partial<ProjectData>) => void;
}

const KickoffView: React.FC<KickoffViewProps> = ({ assets, projectData, onGenerate, onUpdateProject }) => {
  const [activeTab, setActiveTab] = useState<'briefing' | 'codebase' | 'devops' | 'verify' | 'download'>('briefing');
  const [isZipping, setIsZipping] = useState(false);
  const [isGeneratingDevOps, setIsGeneratingDevOps] = useState(false);
  const [showConfetti, setShowConfetti] = useState(false);
  const [isConsolidating, setIsConsolidating] = useState(false);
  
  const gemini = React.useMemo(() => new GeminiService(), []);
  const { dispatch } = useProject();
  const { addToast } = useToast();

  const generateComplianceReport = () => {
      const cl = projectData.securityContext?.complianceChecklist || [];
      const met = cl.filter(i => i.status === 'Met');
      const pending = cl.filter(i => i.status === 'Pending');
      const na = cl.filter(i => i.status === 'N/A');

      return `# Security Compliance Report
Generated by 0relai on ${new Date().toLocaleDateString()}

## Summary
- **Met:** ${met.length}
- **Pending:** ${pending.length}
- **N/A:** ${na.length}

## Active Requirements
${met.map(i => `- [x] **${i.standard}**: ${i.requirement}\n  - *Action Taken*: ${i.action}`).join('\n')}

## Pending Actions
${pending.map(i => `- [ ] **${i.standard}**: ${i.requirement}\n  - *Required Action*: ${i.action}`).join('\n')}

## Excluded (N/A)
${na.map(i => `- [ ] ~~${i.standard}: ${i.requirement}~~`).join('\n')}
`;
  };

  const handleGenerateDevOps = async () => {
      setIsGeneratingDevOps(true);
      try {
          const config = await gemini.generateDevOpsConfig(projectData);
          dispatch({ type: 'UPDATE_PROJECT_DATA', payload: { devOpsConfig: config } });
          addToast("DevOps configuration generated", "success");
      } catch (e) {
          addToast("Failed to generate DevOps configuration.", "error");
      } finally {
          setIsGeneratingDevOps(false);
      }
  };

  const handleFileUpdate = (path: string, content: string) => {
      const currentStructure = projectData.fileStructure || [];
      const newStructure = upsertFileNode(currentStructure, path, content);
      onUpdateProject({ fileStructure: newStructure });
      addToast(`Updated ${path}`, "success");
  };

  const handleConsolidate = () => {
      if (!confirm("This will merge all generated assets (IaC, Docs, Tasks) into your permanent File Structure. Continue?")) return;
      
      setIsConsolidating(true);
      try {
          const newStructure = consolidateProjectFiles(projectData);
          onUpdateProject({ fileStructure: newStructure });
          addToast("Codebase consolidated successfully", "success");
      } catch (e) {
          addToast("Consolidation failed", "error");
      } finally {
          setIsConsolidating(false);
      }
  };

  const handleDownloadBundle = async () => {
    setIsZipping(true);
    try {
      const zip = new JSZip();

      // 1. Generate core manifests freshly to ensure they match final state
      try {
        const manifest = await gemini.generateProjectManifest(projectData);
        if (manifest.filename && manifest.content) {
            zip.file(manifest.filename, manifest.content);
        }
      } catch (e) { console.warn("Manifest gen failed", e); }

      try {
        const gitScript = await gemini.generateGitScript(projectData);
        zip.file("setup_repo.sh", gitScript);
      } catch (e) { console.warn("Git script gen failed", e); }

      try {
        const driftScript = await gemini.generateDriftCheckScript(projectData);
        zip.file("drift-check.js", driftScript);
      } catch (e) { console.warn("Drift script gen failed", e); }

      // 2. Build the Virtual Filesystem from all app state (Tasks, Editors, etc)
      const vfs = buildVirtualFileSystem(projectData);
      vfs.forEach(file => {
          // Avoid overwriting manifest if we just generated it, unless vfs has it from editor
          if (file.content) {
              zip.file(file.path, file.content);
          }
      });

      // 3. Documentation & Meta (These might duplicate if VFS caught them, but zip handles overwrite)
      zip.file("README.md", `# ${projectData.name}\n\n${projectData.initialIdea}\n\n## Stack\n- Frontend: ${projectData.architecture?.stack?.frontend || 'N/A'}\n- Backend: ${projectData.architecture?.stack?.backend || 'N/A'}\n- DB: ${projectData.architecture?.stack?.database || 'N/A'}\n\n## Setup\n1. Run \`./setup_repo.sh\` to init git\n2. Run \`docker-compose up\`\n3. Verify Integrity: \`node drift-check.js\``);
      zip.file("blueprint-metadata.json", JSON.stringify(projectData, null, 2));
      zip.file("docs/COMPLIANCE_REPORT.md", generateComplianceReport());
      
      if (assets) {
        zip.file("docs/KICKOFF_BRIEFING.md", assets);
      }

      if (projectData.apiSpec) {
        const apiMd = `# API Specification\n\nAuth: ${projectData.apiSpec.authMechanism}\n\n` + 
          projectData.apiSpec.endpoints.map(e => `## ${e.method} ${e.path}\n${e.summary}\n\nRequest:\n\`\`\`json\n${e.requestBody || '{}'}\n\`\`\`\n\nResponse:\n\`\`\`json\n${e.responseSuccess || '{}'}\n\`\`\``).join('\n\n');
        zip.file("docs/API_SPEC.md", apiMd);
      }

      // 4. Plugins
      if (projectData.activePlugins && projectData.activePlugins.length > 0) {
          for (const pluginId of projectData.activePlugins) {
              const plugin = getPluginById(pluginId);
              if (plugin) {
                  try {
                      console.log(`Executing plugin: ${plugin.name}`);
                      const files = await plugin.execute(projectData);
                      files.forEach(f => zip.file(f.filename, f.content));
                  } catch (e) {
                      console.error(`Plugin ${plugin.name} failed`, e);
                  }
              }
          }
      }

      // 5. Obsidian Vault Folder (Documentation Site)
      try {
          const vaultBlob = await generateMarkdownVault(projectData);
          const vaultZip = await JSZip.loadAsync(vaultBlob);
          // Merge vault zip into main zip under docs/vault
          vaultZip.forEach(async (relativePath, file) => {
              const content = await file.async('string');
              zip.file(`docs/vault/${relativePath}`, content);
          });
      } catch(e) {
          console.warn("Vault generation failed", e);
      }

      const content = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(content);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${projectData.name.toLowerCase().replace(/\s+/g, '-')}-0relai-bundle.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      // Celebrate!
      setShowConfetti(true);
      setTimeout(() => setShowConfetti(false), 5000);

    } catch (e) {
      console.error("Failed to zip", e);
      addToast("Bundle generation failed.", "error");
    } finally {
      setIsZipping(false);
    }
  };

  return (
    <div className="animate-slide-in-up h-full flex flex-col relative">
      {showConfetti && <Confetti />}
      
      <div className="flex justify-between items-center mb-6">
          <h2 className="text-2xl sm:text-3xl font-bold text-brand-text">Project Handover</h2>
          
          <div className="bg-white/5 p-1 rounded-xl flex overflow-x-auto max-w-[60vw]">
                <button 
                  onClick={() => setActiveTab('briefing')}
                  className={`px-4 py-2 text-xs font-bold uppercase rounded-lg transition-all whitespace-nowrap ${activeTab === 'briefing' ? 'bg-brand-primary text-white shadow-lg' : 'text-glass-text-secondary hover:text-white'}`}
                >
                  Briefing
                </button>
                <button 
                  onClick={() => setActiveTab('codebase')}
                  className={`px-4 py-2 text-xs font-bold uppercase rounded-lg transition-all whitespace-nowrap ${activeTab === 'codebase' ? 'bg-brand-primary text-white shadow-lg' : 'text-glass-text-secondary hover:text-white'}`}
                >
                  Codebase Preview
                </button>
                <button 
                  onClick={() => setActiveTab('devops')}
                  className={`px-4 py-2 text-xs font-bold uppercase rounded-lg transition-all whitespace-nowrap ${activeTab === 'devops' ? 'bg-brand-primary text-white shadow-lg' : 'text-glass-text-secondary hover:text-white'}`}
                >
                  DevOps
                </button>
                <button 
                  onClick={() => setActiveTab('verify')}
                  className={`px-4 py-2 text-xs font-bold uppercase rounded-lg transition-all whitespace-nowrap ${activeTab === 'verify' ? 'bg-brand-primary text-white shadow-lg' : 'text-glass-text-secondary hover:text-white'}`}
                >
                  Verify
                </button>
                <button 
                  onClick={() => setActiveTab('download')}
                  className={`px-4 py-2 text-xs font-bold uppercase rounded-lg transition-all whitespace-nowrap ${activeTab === 'download' ? 'bg-brand-primary text-white shadow-lg' : 'text-glass-text-secondary hover:text-white'}`}
                >
                  Export
                </button>
          </div>
      </div>
      
      <div className="flex-grow overflow-y-auto custom-scrollbar p-1">
        
        {/* TAB: BRIEFING */}
        {activeTab === 'briefing' && (
            <div>
                {!assets ? (
                    <div className="text-center py-20 glass-panel rounded-3xl border-brand-primary/20 border">
                    <div className="w-24 h-24 bg-gradient-to-br from-brand-primary/20 to-brand-accent/20 rounded-full flex items-center justify-center mx-auto mb-6 border border-brand-primary/30 relative">
                        <div className="absolute inset-0 bg-brand-primary/10 rounded-full animate-ping"></div>
                        <span className="text-5xl relative z-10">🚀</span>
                    </div>
                    <h3 className="text-2xl font-bold text-white mb-2">Architectural Blueprint Finalized</h3>
                    <p className="text-lg text-blue-200 mb-8 max-w-xl mx-auto px-4">
                        All layers of the stack have been engineered. Ready to compile the final developer bundle and kickoff instructions.
                    </p>
                    <button
                        onClick={onGenerate}
                        className="px-10 py-4 glass-button-primary text-white font-bold text-lg rounded-2xl shadow-xl hover:scale-105 transition-all"
                    >
                        Initialize Briefing
                    </button>
                    </div>
                ) : (
                    <div className="glass-panel p-8 rounded-3xl">
                        <div className="flex items-center gap-3 mb-6 border-b border-white/10 pb-4">
                            <span className="text-2xl">📝</span>
                            <h3 className="text-2xl font-bold text-white">Kickoff Briefing</h3>
                        </div>
                        <MarkdownRenderer content={assets} />
                    </div>
                )}
            </div>
        )}

        {/* TAB: CODEBASE PREVIEW */}
        {activeTab === 'codebase' && (
            <div className="animate-fade-in space-y-4">
                <div className="flex justify-between items-center bg-slate-800/50 p-4 rounded-xl border border-white/5">
                    <div className="flex items-center gap-3">
                        <div className="text-2xl">💾</div>
                        <div>
                            <h3 className="text-white font-bold text-sm">Unified Codebase</h3>
                            <p className="text-xs text-glass-text-secondary">
                                Review and edit all generated files before export.
                            </p>
                        </div>
                    </div>
                    <button 
                        onClick={handleConsolidate}
                        disabled={isConsolidating}
                        className="bg-brand-secondary/20 hover:bg-brand-secondary/40 text-brand-secondary border border-brand-secondary/50 px-4 py-2 rounded-lg text-xs font-bold transition-all flex items-center gap-2"
                        title="Permanently save all AI-generated files into the project structure"
                    >
                        {isConsolidating ? <span className="animate-spin">⟳</span> : <span>📥</span>}
                        Consolidate Assets
                    </button>
                </div>
                <CodebaseViewer 
                    projectData={projectData} 
                    onFileUpdate={handleFileUpdate}
                />
            </div>
        )}

        {/* TAB: DEVOPS */}
        {activeTab === 'devops' && (
            <div className="space-y-6">
                {!projectData.devOpsConfig ? (
                    <div className="text-center py-16 bg-slate-900/50 rounded-3xl border border-white/5">
                        <div className="w-20 h-20 bg-slate-800 rounded-full flex items-center justify-center mx-auto mb-6 text-4xl">
                            ⚙️
                        </div>
                        <h3 className="text-xl font-bold text-white mb-2">DevOps Engineering</h3>
                        <p className="text-glass-text-secondary max-w-md mx-auto mb-8">
                            Generate production-ready Dockerfiles, Orchestration scripts, and GitHub Actions pipelines tailored to your architecture.
                        </p>
                        <button
                            onClick={handleGenerateDevOps}
                            disabled={isGeneratingDevOps}
                            className="bg-brand-secondary hover:bg-blue-600 text-white px-8 py-3 rounded-xl font-bold shadow-lg transition-all flex items-center gap-2 mx-auto disabled:opacity-50"
                        >
                            {isGeneratingDevOps ? (
                                <>
                                    <div className="w-4 h-4 border-2 border-white/50 border-t-white rounded-full animate-spin"></div>
                                    <span>Engineering Pipeline...</span>
                                </>
                            ) : (
                                <span>Generate CI/CD Assets</span>
                            )}
                        </button>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                        <div className="bg-[#0f172a] rounded-xl border border-glass-border overflow-hidden flex flex-col h-[500px]">
                            <div className="bg-slate-800 px-4 py-2 border-b border-glass-border flex justify-between items-center">
                                <span className="text-xs font-bold text-blue-300 font-mono">Dockerfile</span>
                                <button onClick={() => navigator.clipboard.writeText(projectData.devOpsConfig?.dockerfile || '')} className="text-xs text-slate-400 hover:text-white">Copy</button>
                            </div>
                            <pre className="p-4 overflow-auto custom-scrollbar text-xs font-mono text-slate-300 flex-grow">
                                {projectData.devOpsConfig.dockerfile}
                            </pre>
                        </div>

                        <div className="bg-[#0f172a] rounded-xl border border-glass-border overflow-hidden flex flex-col h-[500px]">
                            <div className="bg-slate-800 px-4 py-2 border-b border-glass-border flex justify-between items-center">
                                <span className="text-xs font-bold text-purple-300 font-mono">.github/workflows/deploy.yml</span>
                                <button onClick={() => navigator.clipboard.writeText(projectData.devOpsConfig?.ciPipeline || '')} className="text-xs text-slate-400 hover:text-white">Copy</button>
                            </div>
                            <pre className="p-4 overflow-auto custom-scrollbar text-xs font-mono text-slate-300 flex-grow">
                                {projectData.devOpsConfig.ciPipeline}
                            </pre>
                        </div>

                        <div className="lg:col-span-2 bg-slate-800/50 p-6 rounded-xl border border-white/5">
                            <h3 className="text-lg font-bold text-white mb-4">Deployment Strategy</h3>
                            <MarkdownRenderer content={projectData.devOpsConfig.deploymentGuide} />
                        </div>
                    </div>
                )}
            </div>
        )}

        {/* TAB: VERIFY (Drift Analysis) */}
        {activeTab === 'verify' && (
            <DriftAnalyzer 
                plannedStructure={projectData.fileStructure || []} 
                onSyncBlueprint={(newStructure) => onUpdateProject({ fileStructure: newStructure })}
            />
        )}

        {/* TAB: DOWNLOAD */}
        {activeTab === 'download' && (
            <div className="flex flex-col items-center justify-center min-h-[400px]">
                <div className="bg-gradient-to-br from-slate-800 to-slate-900 p-10 rounded-3xl border border-brand-secondary/40 shadow-2xl relative overflow-hidden group max-w-xl w-full text-center">
                    <div className="absolute -top-10 -right-10 w-40 h-40 bg-brand-secondary/10 rounded-full blur-3xl group-hover:bg-brand-secondary/20 transition-all"></div>
                    
                    <h3 className="text-3xl font-bold text-white mb-4 relative z-10">Ready for Launch</h3>
                    <p className="text-slate-300 mb-8 relative z-10 leading-relaxed">
                        This encrypted ZIP contains everything a professional developer or AI agent needs to build your project from scratch.
                    </p>
                    
                    <div className="grid grid-cols-2 gap-4 text-left mb-8 relative z-10">
                        {[
                        'Complete File Scaffold',
                        'Dependency Manifests',
                        '.cursorrules (Agent Brain)',
                        'Drift Detection Script',
                        'Git & Docker Configs',
                        'Full Obsidian Documentation',
                        ].map((item, idx) => (
                        <div key={idx} className="flex items-center gap-2 text-sm text-slate-400">
                            <svg className="w-4 h-4 text-brand-accent flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                            <span>{item}</span>
                        </div>
                        ))}
                    </div>

                    <button
                        onClick={handleDownloadBundle}
                        disabled={isZipping}
                        className="w-full py-4 glass-button-primary text-white font-bold rounded-2xl shadow-2xl flex items-center justify-center gap-3 disabled:opacity-50 disabled:cursor-not-allowed transform hover:scale-[1.02] transition-all relative z-10"
                    >
                        {isZipping ? (
                            <div className="flex items-center gap-2">
                                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                                <span>Minting Codebase...</span>
                            </div>
                        ) : (
                            <>
                                <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                                <span className="text-lg">Download ZIP Bundle</span>
                            </>
                        )}
                    </button>
                </div>
                
                <div className="mt-8 text-center text-sm text-glass-text-secondary max-w-md">
                    <p>After downloading, run <code className="bg-white/10 px-1 py-0.5 rounded text-white font-mono">./setup_repo.sh</code> to initialize Git and <code className="bg-white/10 px-1 py-0.5 rounded text-white font-mono">node drift-check.js</code> to verify integrity.</p>
                </div>
            </div>
        )}
      </div>
    </div>
  );
};

export default KickoffView;
