
import React, { useState } from 'react';
import MarkdownRenderer from './MarkdownRenderer';
import { ProjectData, FileNode } from '../types';
import JSZip from 'jszip';

interface KickoffViewProps {
  assets?: string;
  projectData: ProjectData;
  onGenerate: () => void;
}

const KickoffView: React.FC<KickoffViewProps> = ({ assets, projectData, onGenerate }) => {
  const [isZipping, setIsZipping] = useState(false);

  // Helper: Get comment syntax based on file extension
  const getCommentSyntax = (filename: string, content: string): string | null => {
    const lower = filename.toLowerCase();
    
    // Files that don't support comments easily or at all in this context
    if (lower.endsWith('.json') || lower.endsWith('.txt') || lower.endsWith('.md')) return null;

    if (lower.endsWith('.html') || lower.endsWith('.xml') || lower.endsWith('.svg')) {
        return `<!-- ${content} -->`;
    }
    
    if (lower.endsWith('.css')) {
        return `/* ${content} */`;
    }
    
    if (lower.endsWith('.py') || lower.endsWith('.sh') || lower.endsWith('.rb') || lower.endsWith('.yaml') || lower.endsWith('.yml') || lower.endsWith('.toml') || lower.endsWith('.dockerfile') || lower.includes('dockerfile')) {
        return `# ${content}`;
    }

    // Default for JS, TS, Java, C#, Go, Rust, etc.
    return `// ${content}`;
  };

  // Helper: Generate shell script content from file structure
  const generateScaffoldScript = (nodes: FileNode[]): string => {
    let script = '#!/bin/bash\n\n# 0relai - Auto-Generated Scaffold Script\n';
    script += 'echo "🚀 Initializing project structure..."\n\n';
    
    const traverse = (nodes: FileNode[], path: string) => {
      nodes.forEach(node => {
        const fullPath = path ? `${path}/${node.name}` : node.name;
        if (node.type === 'folder') {
          script += `mkdir -p "${fullPath}"\n`;
          if (node.children) traverse(node.children, fullPath);
        } else {
          script += `touch "${fullPath}"\n`;
          const comment = getCommentSyntax(node.name, node.description.replace(/"/g, '\\"'));
          if (comment) {
             script += `echo "${comment}" >> "${fullPath}"\n`;
          }
        }
      });
    };

    if (nodes) traverse(nodes, '.');
    
    script += '\necho "✅ Scaffolding complete!"\n';
    return script;
  };

  // Helper: Generate a robust README
  const generateReadme = () => {
    return `# ${projectData.projectType}: ${projectData.initialIdea.substring(0, 50)}...

## Overview
${projectData.initialIdea}

## Tech Stack
- **Frontend:** ${projectData.architecture?.stack.frontend}
- **Backend:** ${projectData.architecture?.stack.backend}
- **Database:** ${projectData.architecture?.stack.database}

## Architecture
${projectData.architecture?.stack.rationale}

## Setup
1. Run \`./scaffold.sh\` to create the directory structure.
2. Install dependencies (see generated config file).

*Generated by 0relai (Zero Reliance)*
`;
  };

  // Helper: Generate Dependency Config File
  const generateDependencyConfig = () => {
    const deps = projectData.architecture?.dependencies || [];
    const backend = projectData.architecture?.stack.backend?.toLowerCase() || '';
    const frontend = projectData.architecture?.stack.frontend?.toLowerCase() || '';
    
    const isNode = backend.includes('node') || backend.includes('next') || frontend.includes('react') || frontend.includes('vue') || frontend.includes('angular');
    const isPython = backend.includes('python') || backend.includes('django') || backend.includes('flask') || backend.includes('fastapi');
    
    if (isNode) {
        const pkg = {
            name: "0relai-generated",
            version: "0.1.0",
            description: projectData.initialIdea.substring(0, 100),
            scripts: {
                "dev": "echo 'Update scripts based on framework'",
                "build": "echo 'Update scripts based on framework'",
                "start": "node index.js"
            },
            dependencies: deps.reduce((acc, dep) => {
                acc[dep.name] = "latest";
                return acc;
            }, {} as Record<string, string>)
        };
        return { name: "package.json", content: JSON.stringify(pkg, null, 2) };
    } 
    
    if (isPython) {
        const content = deps.map(d => `${d.name} # ${d.description}`).join('\n');
        return { name: "requirements.txt", content };
    }

    // Fallback
    const content = deps.map(d => `${d.name} - ${d.description}`).join('\n');
    return { name: "dependencies_list.txt", content };
  };

  const handleDownloadBundle = async () => {
    setIsZipping(true);
    try {
      const zip = new JSZip();

      // 1. Add Scaffold Script
      if (projectData.fileStructure) {
        zip.file("scaffold.sh", generateScaffoldScript(projectData.fileStructure));
      }

      // 2. Add Cursor Rules / System Prompt
      if (projectData.agentRules) {
        zip.file(".cursorrules", projectData.agentRules);
        zip.file("SYSTEM_PROMPT.md", projectData.agentRules);
      }

      // 3. Add Schema
      if (projectData.schema) {
        if (projectData.schema.prismaSchema) zip.file("schema.prisma", projectData.schema.prismaSchema);
        if (projectData.schema.sqlSchema) zip.file("schema.sql", projectData.schema.sqlSchema);
      }

      // 4. Add Docs & Config
      zip.file("README.md", generateReadme());
      zip.file("SPEC.md", JSON.stringify(projectData, null, 2)); // Full raw data
      
      const depConfig = generateDependencyConfig();
      zip.file(depConfig.name, depConfig.content);
      
      if (assets) {
        zip.file("KICKOFF_NOTES.md", assets);
      }

      // Generate blob
      const content = await zip.generateAsync({ type: "blob" });
      
      // Trigger download
      const url = URL.createObjectURL(content);
      const a = document.createElement("a");
      a.href = url;
      a.download = "0relai-bundle.zip";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

    } catch (e) {
      console.error("Failed to zip", e);
      alert("Failed to generate zip file.");
    } finally {
      setIsZipping(false);
    }
  };

  return (
    <div className="animate-slide-in-up">
      <h2 className="text-2xl sm:text-3xl font-bold text-brand-text mb-6 text-center">Mission Control</h2>
      
      {!assets ? (
        <div className="text-center py-12">
          <div className="w-20 h-20 bg-slate-800 rounded-full flex items-center justify-center mx-auto mb-6 border-2 border-slate-600">
             <span className="text-4xl">🚀</span>
          </div>
          <p className="text-lg text-blue-200 mb-8 max-w-2xl mx-auto">
            All systems check complete. You have a plan, a design, and a blueprint. 
            Ready to generate your launch assets?
          </p>
          <button
            onClick={onGenerate}
            className="px-8 py-3 bg-brand-secondary text-white font-bold rounded-lg shadow-lg hover:bg-blue-500 transition-all transform hover:scale-105"
          >
            Initiate Launch Sequence
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Left Col: Soft Assets */}
          <div className="lg:col-span-2 space-y-8">
             <div className="bg-slate-800/50 p-6 rounded-lg ring-1 ring-slate-700">
                <h3 className="text-xl font-bold text-brand-accent mb-4 border-b border-slate-700 pb-2">Kickoff Briefing</h3>
                <MarkdownRenderer content={assets} />
             </div>
          </div>

          {/* Right Col: Technical Handover */}
          <div className="lg:col-span-1 space-y-6">
             <div className="bg-gradient-to-br from-slate-800 to-slate-900 p-6 rounded-lg ring-1 ring-brand-secondary shadow-2xl">
                <div className="flex items-center gap-3 mb-4">
                    <span className="text-3xl">📦</span>
                    <h3 className="text-xl font-bold text-white">Developer Bundle</h3>
                </div>
                <p className="text-sm text-slate-300 mb-6">
                    Download the comprehensive starter kit containing all generated specs, rules, config files, and scaffold scripts.
                </p>
                
                <ul className="space-y-2 mb-6 text-sm text-slate-400 font-mono">
                    <li className="flex items-center gap-2">
                        <svg className="w-4 h-4 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                        scaffold.sh
                    </li>
                    <li className="flex items-center gap-2">
                        <svg className="w-4 h-4 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                        .cursorrules
                    </li>
                    <li className="flex items-center gap-2">
                        <svg className="w-4 h-4 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                        package.json / requirements.txt
                    </li>
                     <li className="flex items-center gap-2">
                        <svg className="w-4 h-4 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                        README.md
                    </li>
                </ul>

                <button
                    onClick={handleDownloadBundle}
                    disabled={isZipping}
                    className="w-full py-3 bg-brand-secondary hover:bg-blue-500 text-white font-bold rounded shadow transition-all flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                    {isZipping ? (
                        <span>Compressing...</span>
                    ) : (
                        <>
                            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                            Download Bundle (.zip)
                        </>
                    )}
                </button>
             </div>

             <div className="bg-green-900/20 p-6 rounded-lg ring-1 ring-green-500/50 text-center">
                <h3 className="text-lg font-bold text-green-300 mb-2">Ready to Build?</h3>
                <p className="text-sm text-green-100">
                    Unzip the bundle, run <code>./scaffold.sh</code>, and open your IDE. Your AI Agent will know exactly what to do thanks to the included rules.
                </p>
             </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default KickoffView;
