
import { PluginDefinition, ProjectData } from '../types';

// Helper to generate Helm Charts
const generateHelmChart = (project: ProjectData) => {
    const appName = project.name.toLowerCase().replace(/[^a-z0-9]/g, '-');
    
    const chartYaml = `apiVersion: v2
name: ${appName}
description: A Helm chart for ${project.name}
type: application
version: 0.1.0
appVersion: "1.0.0"
`;

    const valuesYaml = `replicaCount: 2

image:
  repository: ${appName}
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: ${appName}.local
      paths:
        - path: /
          pathType: ImplementationSpecific
`;

    const deploymentYaml = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "${appName}.fullname" . }}
  labels:
    {{- include "${appName}.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "${appName}.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "${appName}.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
`;

    return [
        { filename: `helm/${appName}/Chart.yaml`, content: chartYaml },
        { filename: `helm/${appName}/values.yaml`, content: valuesYaml },
        { filename: `helm/${appName}/templates/deployment.yaml`, content: deploymentYaml }
    ];
};

const generateLicense = (project: ProjectData) => {
    const year = new Date().getFullYear();
    const author = project.author || 'The 0relai Architect';
    
    const mit = `MIT License

Copyright (c) ${year} ${author}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`;

    return [{ filename: 'LICENSE', content: mit }];
};

const generateReadmeBadges = (project: ProjectData) => {
    // This plugin doesn't create a new file, but appends to README if handled by the zipper, 
    // or creates a separate snippet file for now.
    const badges = `
<!-- Badges generated by 0relai Plugin -->
![Build Status](https://img.shields.io/github/actions/workflow/status/${project.author || 'user'}/${project.name.toLowerCase().replace(/ /g, '-')}?style=flat-square)
![License](https://img.shields.io/badge/license-MIT-blue?style=flat-square)
![Version](https://img.shields.io/badge/version-1.0.0-orange?style=flat-square)
![Powered By](https://img.shields.io/badge/Architected_with-0relai-indigo?style=flat-square)
`;
    return [{ filename: 'docs/BADGES.md', content: badges }];
};

const generateVscodeSettings = (project: ProjectData) => {
    const settings = {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "files.exclude": {
            "**/.git": true,
            "**/.DS_Store": true
        },
        "search.exclude": {
            "**/node_modules": true,
            "**/dist": true
        }
    };
    
    const extensions = {
        "recommendations": [
            "esbenp.prettier-vscode",
            "dbaeumer.vscode-eslint"
        ]
    };

    return [
        { filename: '.vscode/settings.json', content: JSON.stringify(settings, null, 2) },
        { filename: '.vscode/extensions.json', content: JSON.stringify(extensions, null, 2) }
    ];
};

export const PLUGIN_REGISTRY: PluginDefinition[] = [
    {
        id: 'k8s-helm',
        name: 'Kubernetes Helm Generator',
        description: 'Automatically creates a production-ready Helm chart scaffold based on your project name.',
        version: '1.2.0',
        author: 'CloudNative Corp',
        icon: '☸️',
        category: 'DevOps',
        execute: async (p) => generateHelmChart(p)
    },
    {
        id: 'license-gen',
        name: 'MIT License Auto-Gen',
        description: 'Adds a standard MIT License file with the current year and author name.',
        version: '1.0.0',
        author: 'LegalBot',
        icon: '⚖️',
        category: 'Docs',
        execute: async (p) => generateLicense(p)
    },
    {
        id: 'readme-badges',
        name: 'Shields.io Badges',
        description: 'Generates a markdown snippet with CI/CD, License, and Version badges.',
        version: '0.9.0',
        author: 'Community',
        icon: '🛡️',
        category: 'Docs',
        execute: async (p) => generateReadmeBadges(p)
    },
    {
        id: 'vscode-config',
        name: 'VS Code Workspace',
        description: 'Pre-configures .vscode settings and recommended extensions for consistency.',
        version: '2.1.0',
        author: 'MS Fan',
        icon: '📝',
        category: 'Code',
        execute: async (p) => generateVscodeSettings(p)
    }
];

export const getPluginById = (id: string) => PLUGIN_REGISTRY.find(p => p.id === id);
